/*
  pt: the shared backend for every tool in the pt repo.
  One Cloudflare Worker, one D1 database (bound as "DB"). Tools identify
  themselves with a short id, so their sessions never mix.

  This file lives in the repo at pt/_backend/pt-worker.js and is deployed by
  pasting it into the Cloudflare dashboard. It contains no secrets and never
  should. Secrets (future API keys) live in the worker's Settings on Cloudflare.

  ONE-TIME DATABASE SETUP (paste into the D1 console):
  CREATE TABLE kv (room TEXT, path TEXT, value TEXT, updated INTEGER, PRIMARY KEY (room, path));

  ENDPOINTS
    GET  /api/health                              -> {ok, gatedTools}
    GET  /api/state?tool=pyc&code=ABCD            -> the whole session as nested JSON
    POST /api/create {tool, code, sk}             -> start a session; registers its session key
    POST /api/set    {tool, code, path, value}    -> write one value
    POST /api/claim  {tool, code, path, value}    -> atomic seat claim, {ok:true|false}
    POST /api/clear  {tool, code}                 -> delete the session

  SETTINGS (Worker > Settings > Variables and Secrets)
    GATED_TOOLS   Variable. Optional. Comma-separated tool ids that require a
                  session key. If unset, the GATED_TOOLS_DEFAULT list in the code
                  below applies, so gating works with no dashboard settings at all.
                  The key is generated by the tool when a facilitator starts a
                  session and rides inside the join link, so participants never
                  type anything.
    ALLOW_ORIGIN  Variable. Optional. Overrides the ALLOW_ORIGIN_DEFAULT list in
                  the code below, which locks the worker to the Pages site with no
                  dashboard settings needed.

  RETENTION
    A daily schedule (Settings > Triggers > Cron, e.g. "0 4 * * *") runs the
    scheduled() handler below, which deletes any session untouched for 7 days.
    Discussion notes should not outlive their usefulness.

  LATER, WHEN A PROTOTYPE NEEDS IT
    AI proxy: add a secret ANTHROPIC_API_KEY, then uncomment the /api/ai block.
      It only answers requests carrying a valid session key for a gated tool,
      so only people inside a real session can spend the budget.
    Collecting responses (forms, polls, waitlists): add a /api/submit route
      writing append-only rows, keyed the same way (tool + a collection name).
*/

var RETENTION_DAYS = 7;

/* Which tools require a session key. Edit this list and redeploy to change it.
   A GATED_TOOLS variable in the dashboard, if you ever set one, overrides this. */
var GATED_TOOLS_DEFAULT = 'pyc';

/* Which origins may call this worker. Edit and redeploy to change it.
   An ALLOW_ORIGIN variable in the dashboard, if you ever set one, overrides this.
   Requests with no Origin header (health checks, curl) always pass. */
var ALLOW_ORIGIN_DEFAULT = 'https://ep.github.io';

export default {
  async fetch(request, env) {
    var url = new URL(request.url);

    /* ---- origins ---- */
    var reqOrigin = request.headers.get('Origin') || '';
    var allowList = (env.ALLOW_ORIGIN || ALLOW_ORIGIN_DEFAULT).split(',').map(function (s) { return s.trim(); }).filter(Boolean);
    var allowOrigin = '*';
    if (allowList.length) {
      allowOrigin = allowList.indexOf(reqOrigin) > -1 ? reqOrigin : allowList[0];
    }
    var cors = {
      'Access-Control-Allow-Origin': allowOrigin,
      'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, X-Session-Key',
      'Vary': 'Origin'
    };
    if (request.method === 'OPTIONS') return new Response(null, { headers: cors });

    function json(obj, status) {
      return new Response(JSON.stringify(obj), {
        status: status || 200,
        headers: Object.assign({ 'Content-Type': 'application/json' }, cors)
      });
    }

    var gatedTools = (env.GATED_TOOLS || GATED_TOOLS_DEFAULT).split(',').map(function (s) { return s.trim().toLowerCase(); }).filter(Boolean);

    if (url.pathname === '/api/health') return json({ ok: true, gatedTools: gatedTools });

    if (allowList.length && reqOrigin && allowList.indexOf(reqOrigin) === -1) {
      return json({ error: 'origin not allowed' }, 403);
    }

    function parseTool(tool) {
      var t = (tool || '').toLowerCase();
      return /^[a-z0-9-]{1,12}$/.test(t) ? t : null;
    }
    function roomOf(tool, code) {
      var c = (code || '').toUpperCase();
      if (!/^[A-Z]{4,8}$/.test(c)) return null;
      return tool + ':' + c;
    }
    async function storedKey(room) {
      var row = await env.DB.prepare('SELECT value FROM kv WHERE room = ? AND path = ?').bind(room, '_sk').first();
      return row ? JSON.parse(row.value) : null;
    }

    try {
      if (url.pathname === '/api/state' && request.method === 'GET') {
        var tool = parseTool(url.searchParams.get('tool'));
        if (!tool) return json({ error: 'bad tool' }, 400);
        var room = roomOf(tool, url.searchParams.get('code'));
        if (!room) return json({ error: 'bad code' }, 400);
        var rs = await env.DB.prepare('SELECT path, value FROM kv WHERE room = ?').bind(room).all();
        if (!rs.results.length) return json({ state: null });
        if (gatedTools.indexOf(tool) > -1) {
          var sk = null;
          for (var k = 0; k < rs.results.length; k++) {
            if (rs.results[k].path === '_sk') sk = JSON.parse(rs.results[k].value);
          }
          if (sk && request.headers.get('X-Session-Key') !== sk) return json({ error: 'locked' }, 401);
        }
        var state = {};
        for (var r = 0; r < rs.results.length; r++) {
          if (rs.results[r].path.charAt(0) === '_') continue; /* internals never leave the notebook */
          var parts = rs.results[r].path.split('/');
          var node = state;
          for (var i = 0; i < parts.length - 1; i++) {
            node[parts[i]] = node[parts[i]] || {};
            node = node[parts[i]];
          }
          node[parts[parts.length - 1]] = JSON.parse(rs.results[r].value);
        }
        return json({ state: state });
      }

      if (request.method === 'POST') {
        var body = await request.json();
        var ptool = parseTool(body.tool);
        if (!ptool) return json({ error: 'bad tool' }, 400);
        var proom = roomOf(ptool, body.code);
        if (!proom) return json({ error: 'bad code' }, 400);
        var gated = gatedTools.indexOf(ptool) > -1;

        if (url.pathname === '/api/create') {
          var newSk = typeof body.sk === 'string' && /^[A-Za-z0-9]{8,32}$/.test(body.sk) ? body.sk : null;
          if (gated && !newSk) return json({ error: 'bad key' }, 400);
          var cres = await env.DB.prepare(
            'INSERT INTO kv (room, path, value, updated) VALUES (?,?,?,?) ' +
            'ON CONFLICT(room, path) DO NOTHING'
          ).bind(proom, '_sk', JSON.stringify(newSk || true), Date.now()).run();
          return json({ ok: cres.meta.changes > 0 });
        }

        /* everything below touches an existing session; gated tools must prove membership */
        if (gated) {
          var haveSk = await storedKey(proom);
          if (!haveSk || request.headers.get('X-Session-Key') !== haveSk) {
            return json({ error: 'locked' }, 401);
          }
        }

        if (url.pathname === '/api/set') {
          if (typeof body.path !== 'string' || body.path.length > 40 || !/^[A-Za-z0-9_/]+$/.test(body.path) || body.path.charAt(0) === '_') {
            return json({ error: 'bad path' }, 400);
          }
          if (/^(seats|pax)\//.test(body.path)) return json({ error: 'use claim' }, 400);
          var value = JSON.stringify(body.value === undefined ? null : body.value);
          if (value.length > 4000) return json({ error: 'too big' }, 400);
          await env.DB.prepare(
            'INSERT INTO kv (room, path, value, updated) VALUES (?,?,?,?) ' +
            'ON CONFLICT(room, path) DO UPDATE SET value = excluded.value, updated = excluded.updated'
          ).bind(proom, body.path, value, Date.now()).run();
          return json({ ok: true });
        }

        if (url.pathname === '/api/claim') {
          var seatOk = /^seats\/s[1-3]$/.test(body.path || '');
          var paxOk = /^pax\/p([1-9]|1[0-9]|20)$/.test(body.path || '');
          if (!seatOk && !paxOk) return json({ error: 'bad seat' }, 400);
          var claimVal = { claimed: true };
          if (paxOk && body.value && typeof body.value.nick === 'string') {
            var nick = body.value.nick.slice(0, 16).trim();
            if (nick) claimVal = { nick: nick };
          }
          var res = await env.DB.prepare(
            'INSERT INTO kv (room, path, value, updated) VALUES (?,?,?,?) ' +
            'ON CONFLICT(room, path) DO NOTHING'
          ).bind(proom, body.path, JSON.stringify(claimVal), Date.now()).run();
          return json({ ok: res.meta.changes > 0 });
        }

        if (url.pathname === '/api/clear') {
          await env.DB.prepare('DELETE FROM kv WHERE room = ?').bind(proom).run();
          return json({ ok: true });
        }

        /* ---------------------------------------------------------------
           FUTURE: AI PROXY. Add the ANTHROPIC_API_KEY secret first. Kept
           behind the gate check above, so only a live gated session can
           spend budget.

        if (url.pathname === '/api/ai') {
          var upstream = await fetch('https://api.anthropic.com/v1/messages', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'x-api-key': env.ANTHROPIC_API_KEY,
              'anthropic-version': '2023-06-01'
            },
            body: JSON.stringify({
              model: 'claude-sonnet-4-6',
              max_tokens: 1000,
              messages: [{ role: 'user', content: String(body.prompt || '').slice(0, 4000) }]
            })
          });
          var data = await upstream.json();
          return json(data, upstream.status);
        }
        --------------------------------------------------------------- */
      }

      return json({ error: 'not found' }, 404);
    } catch (e) {
      return json({ error: 'server error' }, 500);
    }
  },

  /* the daily sweep: sessions untouched for RETENTION_DAYS vanish whole */
  async scheduled(event, env, ctx) {
    var cutoff = Date.now() - RETENTION_DAYS * 24 * 60 * 60 * 1000;
    await env.DB.prepare(
      'DELETE FROM kv WHERE room IN (SELECT room FROM kv GROUP BY room HAVING MAX(updated) < ?)'
    ).bind(cutoff).run();
  }
};
